# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Laborant_barcode_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Laborant_barcode(object):
    def setupUi(self, Laborant_barcode):
        Laborant_barcode.setObjectName("Laborant_barcode")
        Laborant_barcode.resize(600, 450)
        self.label_21 = QtWidgets.QLabel(Laborant_barcode)
        self.label_21.setGeometry(QtCore.QRect(40, 10, 160, 161))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(73, 140, 81);")
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setLineWidth(5)
        self.label_21.setText("")
        self.label_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(Laborant_barcode)
        self.label_14.setEnabled(True)
        self.label_14.setGeometry(QtCore.QRect(10, 210, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setTextFormat(QtCore.Qt.AutoText)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(Laborant_barcode)
        self.lineEdit.setGeometry(QtCore.QRect(240, 210, 231, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_12 = QtWidgets.QPushButton(Laborant_barcode)
        self.pushButton_12.setGeometry(QtCore.QRect(240, 250, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_20 = QtWidgets.QLabel(Laborant_barcode)
        self.label_20.setEnabled(True)
        self.label_20.setGeometry(QtCore.QRect(470, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_13 = QtWidgets.QPushButton(Laborant_barcode)
        self.pushButton_13.setGeometry(QtCore.QRect(210, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Laborant_barcode)
        self.pushButton_14.setGeometry(QtCore.QRect(200, 370, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_15 = QtWidgets.QLabel(Laborant_barcode)
        self.label_15.setEnabled(True)
        self.label_15.setGeometry(QtCore.QRect(40, 170, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("")
        self.label_15.setTextFormat(QtCore.Qt.AutoText)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")

        self.pushButton_16 = QtWidgets.QPushButton(Laborant_barcode)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 450-31, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(13)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")

        self.retranslateUi(Laborant_barcode)
        QtCore.QMetaObject.connectSlotsByName(Laborant_barcode)

    def retranslateUi(self, Laborant_barcode):
        _translate = QtCore.QCoreApplication.translate
        Laborant_barcode.setWindowTitle(_translate("Laborant_barcode", "Medic"))
        self.label_14.setText(_translate("Laborant_barcode", "Код пробирки"))
        self.lineEdit.setText(_translate("Laborant_barcode", "57"))
        self.pushButton_12.setText(_translate("Laborant_barcode", "Заполнить код пробирки"))
        self.label_20.setText(_translate("Laborant_barcode", "Зянато"))
        self.pushButton_13.setText(_translate("Laborant_barcode", "Считать со сканера"))
        self.pushButton_14.setText(_translate("Laborant_barcode", "Подтвердить"))
        self.label_15.setText(_translate("Laborant_barcode", "57130423901234"))
        self.pushButton_16.setText(_translate("Laborant_barcode", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Laborant_barcode = QtWidgets.QDialog()
    ui = Ui_Laborant_barcode()
    ui.setupUi(Laborant_barcode)
    Laborant_barcode.show()
    sys.exit(app.exec_())
