# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Laborant_service_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choose_Service(object):
    def setupUi(self, Choose_Service):
        Choose_Service.setObjectName("Choose_Service")
        Choose_Service.resize(600, 450)
        font = QtGui.QFont()
        font.setPointSize(9)
        Choose_Service.setFont(font)
        self.label_20 = QtWidgets.QLabel(Choose_Service)
        self.label_20.setEnabled(True)
        self.label_20.setGeometry(QtCore.QRect(170, 0, 270, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(19)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.checkBox = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox.setGeometry(QtCore.QRect(50, 70, 281, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMaximumSize(QtCore.QSize(281, 41))
        self.checkBox.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.checkBox.setToolTipDuration(-1)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_12 = QtWidgets.QPushButton(Choose_Service)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 370, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Choose_Service)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 0, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")


        self.retranslateUi(Choose_Service)
        QtCore.QMetaObject.connectSlotsByName(Choose_Service)

    def retranslateUi(self, Choose_Service):
        _translate = QtCore.QCoreApplication.translate
        Choose_Service.setWindowTitle(_translate("Choose_Service", "Medic"))
        self.label_20.setText(_translate("Choose_Service", "Выберите услуги"))
        self.checkBox.setText(_translate("Choose_Service", "СПИД"))
        self.pushButton_12.setText(_translate("Choose_Service", "Добавить в заказ"))
        self.pushButton_13.setText(_translate("Choose_Service", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Choose_Service = QtWidgets.QDialog()
    ui = Ui_Choose_Service()
    ui.setupUi(Choose_Service)
    Choose_Service.show()
    sys.exit(app.exec_())
