# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Laborant_service_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choose_Service(object):
    def setupUi(self, Choose_Service):
        Choose_Service.setObjectName("Choose_Service")
        Choose_Service.resize(600, 680)
        font = QtGui.QFont()
        font.setPointSize(9)
        Choose_Service.setFont(font)
        self.label_20 = QtWidgets.QLabel(Choose_Service)
        self.label_20.setEnabled(True)
        self.label_20.setGeometry(QtCore.QRect(170, 0, 270, 60))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(19)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("")
        self.label_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")

        self.label_23 = QtWidgets.QLabel(Choose_Service)
        self.label_23.setEnabled(True)
        self.label_23.setGeometry(QtCore.QRect(170, 620, 270, 60))
        font.setPointSize(19)
        self.label_23.setFont(font)
        self.label_23.close()

        self.label_24 = QtWidgets.QLabel(Choose_Service)
        self.label_24.setEnabled(True)
        self.label_24.setGeometry(QtCore.QRect(170, 620, 270, 60))
        font.setPointSize(19)
        self.label_24.setFont(font)
        self.label_24.close()

        self.checkBox = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox.setGeometry(QtCore.QRect(50, 70, 281, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setMaximumSize(QtCore.QSize(281, 41))
        self.checkBox.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.checkBox.setToolTipDuration(-1)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setAutoFillBackground(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")

        self.pushButton_12 = QtWidgets.QPushButton(Choose_Service)
        self.pushButton_12.setGeometry(QtCore.QRect(210, 590, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Choose_Service)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 0, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")

        self.checkBox_2 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 100, 281, 41))
        self.checkBox_2.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_2.setFont(font)

        self.checkBox_3 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_3.setGeometry(QtCore.QRect(50, 130, 281, 41))
        self.checkBox_3.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_3.setFont(font)

        self.checkBox_4 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_4.setGeometry(QtCore.QRect(50, 160, 281, 41))
        self.checkBox_4.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_4.setFont(font)

        self.checkBox_5 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_5.setGeometry(QtCore.QRect(50, 190, 281, 41))
        self.checkBox_5.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_5.setFont(font)

        self.checkBox_6 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_6.setGeometry(QtCore.QRect(50, 220, 281, 41))
        self.checkBox_6.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_6.setFont(font)

        self.checkBox_7 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_7.setGeometry(QtCore.QRect(50, 250, 281, 41))
        self.checkBox_7.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_7.setFont(font)

        self.checkBox_8 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_8.setGeometry(QtCore.QRect(50, 280, 281, 41))
        self.checkBox_8.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_8.setFont(font)

        self.checkBox_9 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_9.setGeometry(QtCore.QRect(50, 310, 281, 41))
        self.checkBox_9.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_9.setFont(font)

        self.checkBox_10 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_10.setGeometry(QtCore.QRect(50, 340, 281, 41))
        self.checkBox_10.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_10.setFont(font)

        self.checkBox_11 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_11.setGeometry(QtCore.QRect(50, 370, 281, 41))
        self.checkBox_11.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_11.setFont(font)

        self.checkBox_12 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_12.setGeometry(QtCore.QRect(50, 400, 281, 41))
        self.checkBox_12.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_12.setFont(font)

        self.checkBox_13 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_13.setGeometry(QtCore.QRect(50, 430, 281, 41))
        self.checkBox_13.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_13.setFont(font)

        self.checkBox_14 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_14.setGeometry(QtCore.QRect(50, 460, 281, 41))
        self.checkBox_14.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_14.setFont(font)

        self.checkBox_15 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_15.setGeometry(QtCore.QRect(50, 490, 281, 41))
        self.checkBox_15.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_15.setFont(font)

        self.checkBox_16 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_16.setGeometry(QtCore.QRect(50, 520, 281, 41))
        self.checkBox_16.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_16.setFont(font)

        self.checkBox_17 = QtWidgets.QCheckBox(Choose_Service)
        self.checkBox_17.setGeometry(QtCore.QRect(50, 550, 310, 41))
        self.checkBox_17.setSizePolicy(sizePolicy)
        font.setPointSize(15)
        self.checkBox_17.setFont(font)


        self.retranslateUi(Choose_Service)
        QtCore.QMetaObject.connectSlotsByName(Choose_Service)

    def retranslateUi(self, Choose_Service):
        _translate = QtCore.QCoreApplication.translate
        Choose_Service.setWindowTitle(_translate("Choose_Service", "Medic"))
        self.label_20.setText(_translate("Choose_Service", "Выберите услуги"))
        self.checkBox.setText(_translate("Choose_Service", "СПИД"))
        self.checkBox_2.setText(_translate("Choose_Service", "ВИЧ"))
        self.checkBox_3.setText(_translate("Choose_Service", "TSH"))
        self.checkBox_4.setText(_translate("Choose_Service", "Амилаза"))
        self.checkBox_5.setText(_translate("Choose_Service", "Альбумин"))
        self.checkBox_6.setText(_translate("Choose_Service", "Креатинин"))
        self.checkBox_7.setText(_translate("Choose_Service", "Билирубин общий"))
        self.checkBox_8.setText(_translate("Choose_Service", "Гепатит В"))
        self.checkBox_9.setText(_translate("Choose_Service", "Гепатит С"))
        self.checkBox_10.setText(_translate("Choose_Service", "Кальций общий"))
        self.checkBox_11.setText(_translate("Choose_Service", "Глюкоза"))
        self.checkBox_12.setText(_translate("Choose_Service", "Ковид IgM"))
        self.checkBox_13.setText(_translate("Choose_Service", "Общий белок"))
        self.checkBox_14.setText(_translate("Choose_Service", "Железо"))
        self.checkBox_15.setText(_translate("Choose_Service", "Сифилис RPR"))
        self.checkBox_16.setText(_translate("Choose_Service", "АТ и АГ к ВИЧ 1/2"))
        self.checkBox_17.setText(_translate("Choose_Service", "Волчаночный антикоагулянт"))


        self.pushButton_12.setText(_translate("Choose_Service", "Добавить в заказ"))
        self.pushButton_13.setText(_translate("Choose_Service", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Choose_Service = QtWidgets.QDialog()
    ui = Ui_Choose_Service()
    ui.setupUi(Choose_Service)
    Choose_Service.show()
    sys.exit(app.exec_())
